import assert from 'node:assert/strict';
import { mkdtemp,rm,mkdir,writeFile,readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import net from 'node:net';
import http from 'node:http';
import { exportSite } from '../src/export.mjs';
import { randomBytes } from 'node:crypto';
import { chromium } from 'playwright';
import sharp from 'sharp';
import { createApp } from '../src/server.mjs';
import { createUser } from '../src/auth.mjs';
import { listContent,putContent } from '../src/content.mjs';
import { modelGLB } from '../tests/fixtures/model.mjs';
import { brandFont } from '../tests/fixtures/font.mjs';
import { getSite,saveSite } from '../src/database.mjs';
import { totp } from '../src/security-crypto.mjs';

const probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
const origin=`http://127.0.0.1:${port}`,dir=await mkdtemp(join(tmpdir(),'cms-browser-')),password='Browser-fixture-password-123!',newPassword='Changed-browser-password-456!',sent=[];
const app=await createApp({dbPath:join(dir,'cms.sqlite'),origin,securityKey:randomBytes(32),mailer:{send:async message=>sent.push(message)}});
let browser,staticServer;
try {
  await createUser(app.db,{email:'admin@example.test',password});await new Promise(resolve=>app.server.listen(port,'127.0.0.1',resolve));
  browser=await chromium.launch({headless:true,...(process.env.CMS_TEST_BROWSER_EXECUTABLE?{executablePath:process.env.CMS_TEST_BROWSER_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-angle=swiftshader']});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
  function watch(target){target.on('pageerror',error=>errors.push(error.message));target.on('console',message=>{if(/violates.*Content Security Policy|Refused to.*Content Security Policy/i.test(message.text()))errors.push(message.text());});}
  watch(page);
  const screenshot=async(target,name)=>{if(process.env.CMS_TEST_SCREENSHOTS){await mkdir(process.env.CMS_TEST_SCREENSHOTS,{recursive:true});await target.screenshot({path:join(process.env.CMS_TEST_SCREENSHOTS,`${name}.png`),fullPage:true});}};
  async function submit(form,path,method='POST') {
    const response=page.waitForResponse(res=>new URL(res.url()).pathname===path && res.request().method()===method);
    await form.locator('button[type=submit]').click();const res=await response;if(!res.ok())throw new Error(`Browser request failed: ${res.status()} ${await res.text().catch(()=>'response unavailable')}`);
  }
  async function login(pwd=password,code='') {
    const form=page.locator('#login-form');await form.locator('[name=email]').fill('admin@example.test');await form.locator('[name=password]').fill(pwd);await form.locator('[name=mfaCode]').fill(code);
    await submit(form,'/api/auth/login');await page.locator('#workspace').waitFor({state:'visible'});await page.locator('[data-view=templates]').waitFor({state:'visible'});
  }
  await page.goto(origin+'/admin/');await login();
  await page.locator('[data-view=templates]').click();await page.locator('#theme-form [value=services]').check();await page.locator('#theme-form [name=primaryColor]').fill('#267651');await page.locator('#theme-form [name=corners]').selectOption('square');await submit(page.locator('#theme-form'),'/api/settings','PUT');
  await page.getByText('ظاهر سایت ذخیره شد.',{exact:true}).waitFor({state:'visible'});await screenshot(page,'theme-panel-desktop');
  await page.locator('[data-view=media]').click();const imageFile=join(dir,'browser.png');await writeFile(imageFile,await sharp({create:{width:600,height:400,channels:3,background:'#d3b18a'}}).png().toBuffer());
  await page.locator('#upload-form [type=file]').setInputFiles(imageFile);await submit(page.locator('#upload-form'),'/api/media');await page.locator('.media-card').waitFor({state:'visible'});
  await page.locator('[data-view=services]').click();await page.locator('#new-content').click();const form=page.locator('#editor-form');
  await form.locator('[name=title]').fill('خدمات طراحی وب');await form.locator('[name=slug]').fill('web-design');await form.locator('[name=excerpt]').fill('طراحی سایت برای معرفی دقیق خدمات کسب‌وکار شما.');await form.locator('[name=body]').fill('متن قدیمی حفظ می‌شود.');
  await form.locator('[data-add-block=hero]').click();const hero=form.locator('[data-block][data-type=hero]');await hero.locator('[data-field=title]').fill('شروع یک همکاری تازه');await hero.locator('[data-field=text]').fill('از شناخت برند تا طراحی و توسعه سایت، مراحل کار روشن و قابل پیگیری است.');await hero.locator('[data-field=mediaId]').selectOption({index:1});await hero.locator('[data-field=alt]').fill('نمونه تصویر معرفی خدمات');
  await form.locator('[data-add-block=cards]').click();let cards=form.locator('[data-block][data-type=cards]');await cards.locator(':scope > label [data-field=title]').fill('مسیر کار');await cards.locator('[data-entry-add]').click();await cards.locator('[data-entry="0"] [data-field=title]').fill('شناخت نیازها');await cards.locator('[data-entry="0"] [data-field=text]').fill('هدف سایت و نیاز مخاطب را مشخص می‌کنیم.');await cards.locator('[data-entry="1"] [data-field=title]').fill('طراحی و توسعه');await cards.locator('[data-entry="1"] [data-field=text]').fill('طرح تأییدشده را با پنل مدیریت پیاده می‌کنیم.');await cards.locator('[data-field=variant]').selectOption('list');await cards.locator('[data-entry-move="1"][data-step="-1"]').click();
  await form.locator('[data-add-block=faq]').click();const faq=form.locator('[data-block][data-type=faq]');await faq.locator(':scope > label [data-field=title]').fill('پرسش‌های متداول');await faq.locator('[data-entry="0"] [data-field=question]').fill('محتوا را می‌توانم تغییر بدهم؟');await faq.locator('[data-entry="0"] [data-field=answer]').fill('بله، صفحات و تصاویر از پنل مدیریت قابل ویرایش‌اند.');
  await submit(form,'/api/content');await page.locator('#editor-dialog').waitFor({state:'hidden'});
  let item=listContent(app.db).find(item=>item.slug==='web-design');assert.equal(item.template,'landing');assert.equal(item.blocks[1].items[0].title,'طراحی و توسعه');assert.equal(item.body,'متن قدیمی حفظ می‌شود.');
  const preview=await context.newPage();watch(preview);await preview.goto(origin+`/api/content/${item.id}/preview`);assert.match(await preview.title(),/خدمات طراحی وب/);assert.equal(await preview.locator('.preview-banner').count(),1);assert.equal(await preview.locator('.section-faq details').count(),1);assert.equal((await fetch(origin+'/services/web-design/')).status,404);await screenshot(preview,'private-preview-desktop');await preview.close();
  await page.locator(`[data-edit="${item.id}"]`).click();await form.locator('[name=template]').selectOption('standard');await form.locator('[name=status]').selectOption('published');await submit(form,`/api/content/${item.id}`,'PUT');await page.locator('#editor-dialog').waitFor({state:'hidden'});
  item=listContent(app.db).find(current=>current.id===item.id);assert.equal(item.template,'standard');assert.equal(item.blocks.length,3);
  const publicPage=await context.newPage();watch(publicPage);await publicPage.goto(origin+'/services/web-design/');assert.equal(await publicPage.locator('body.site-template-services').count(),1);await publicPage.locator('.section-faq summary').click();assert.equal(await publicPage.locator('.section-faq details').getAttribute('open'),'');
  for(const width of [1440,390]){await publicPage.setViewportSize({width,height:1000});assert.ok(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Public page has horizontal overflow');assert.ok(await publicPage.locator('img').evaluate(image=>image.complete&&image.naturalWidth>0));await screenshot(publicPage,`service-${width}`);}
  await page.locator('[data-view=templates]').click();await page.locator('#theme-form [value=corporate]').check();await submit(page.locator('#theme-form'),'/api/settings','PUT');await publicPage.reload();assert.equal(await publicPage.locator('body.site-template-corporate').count(),1);await screenshot(publicPage,'corporate-mobile');
  await page.setViewportSize({width:390,height:844});await page.locator('[data-view=services]').click();await page.locator(`[data-edit="${item.id}"]`).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Editor has horizontal overflow');await screenshot(page,'editor-mobile');await page.locator('#cancel-editor').click();
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-view=designer]').click();await page.locator('[data-new-design=three-hero]').click();await page.locator('#design-dialog').waitFor({state:'visible'});
  const designDialog=page.locator('#design-dialog'),codeFrame=page.frameLocator('#design-preview');
  await codeFrame.locator('canvas[data-renderer=three]').waitFor({state:'visible'});assert.ok(Number(await codeFrame.locator('canvas').getAttribute('data-triangles'))>0,'Three.js must submit real triangles');
  assert.equal(await codeFrame.locator('canvas').evaluate(el=>el.getContext('webgl2').isContextLost()),false);
  assert.equal(await codeFrame.locator('body').evaluate(()=>{try{return parent.document.body.innerHTML;}catch{return 'blocked';}}),'blocked');
  assert.equal(await codeFrame.locator('body').evaluate(()=>{try{return document.cookie;}catch{return 'blocked';}}),'blocked');
  assert.equal(await codeFrame.locator('body').evaluate(()=>{try{return localStorage.length;}catch{return 'blocked';}}),'blocked');
  await codeFrame.locator('#toggle-motion').click();assert.equal(await codeFrame.locator('#toggle-motion').getAttribute('aria-pressed'),'true');
  await designDialog.locator('[data-device=mobile]').click();assert.ok(await codeFrame.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'3D mobile preview must fit');
  await screenshot(page,'designer-three-mobile');await designDialog.locator('[data-code-tab=css]').click();await designDialog.locator('[name=css]').fill((await designDialog.locator('[name=css]').inputValue())+'\n.copy span{letter-spacing:.03em}');
  const auto=await page.waitForResponse(res=>new URL(res.url()).pathname.startsWith('/api/designs/') && res.request().method()==='PUT');assert.equal(auto.status(),200);assert.match(await designDialog.locator('#release-state').innerText(),/منتشر نشده/);
  await designDialog.locator('#design-history').selectOption({index:1});const restoreResponse=page.waitForResponse(res=>res.url().endsWith('/restore') && res.request().method()==='POST');await designDialog.locator('#restore-version').click();assert.equal((await restoreResponse).status(),200);await codeFrame.locator('canvas[data-renderer=three]').waitFor({state:'visible'});assert.equal(app.db.prepare('SELECT published_id FROM designs ORDER BY created_at LIMIT 1').get().published_id,null);
  await designDialog.locator('#release-form [name=currentPassword]').fill(password);const releaseResponse=page.waitForResponse(res=>res.url().endsWith('/publish') && res.request().method()==='POST');await designDialog.locator('#release-form [type=submit]').click();assert.equal((await releaseResponse).status(),200);await designDialog.locator('#release-feedback').getByText('نسخه انتخاب‌شده منتشر شد.',{exact:true}).waitFor();
  const design=app.db.prepare('SELECT * FROM designs ORDER BY created_at LIMIT 1').get();await designDialog.locator('#close-design').click();await designDialog.waitFor({state:'hidden'});
  await page.locator('[data-view=pages]').click();await page.locator('#new-content').click();await form.locator('[name=title]').fill('صفحه اصلی سه‌بعدی');await form.locator('[name=slug]').fill('home');await form.locator('#page-preset').selectOption('home');await form.locator('#apply-page-preset').click();assert.equal(await form.locator('[data-block]').count(),3);await form.locator('#section-preset').selectOption('faq');await form.locator('#apply-section-preset').click();assert.equal(await form.locator('[data-block]').count(),4);await form.locator('#undo-block-change').click();assert.equal(await form.locator('[data-block]').count(),3);
  await form.locator('[data-add-block=code-design]').click();const designBlock=form.locator('[data-type=code-design]');await designBlock.locator('[data-field=designId]').selectOption(design.id);await designBlock.locator('[data-field=title]').fill('تجربه سه‌بعدی برند');await designBlock.locator('[data-field=fallback]').fill('خدمات طراحی سایت اختصاصی برای کسب‌وکار شما.');
  // Native drag with keyboard alternatives retained in the UI.
  await form.locator('[data-order-drag="3"]').dragTo(form.locator('[data-order-drag="0"]'));assert.equal(await form.locator('[data-block="0"]').getAttribute('data-type'),'code-design');
  await submit(form,'/api/content');await page.locator('#editor-dialog').waitFor({state:'hidden'});const home=listContent(app.db).find(i=>i.slug==='home');
  await page.locator(`[data-edit="${home.id}"]`).click();await form.locator('#responsive-preview').click();const pagePreview=page.locator('.page-preview-dialog');await pagePreview.locator('[data-page-device=mobile]').click();await page.frameLocator('.page-preview-dialog iframe').locator('iframe.design-frame').waitFor();await pagePreview.locator('[data-close-page-preview]').click();
  await form.locator('[name=status]').selectOption('published');await submit(form,`/api/content/${home.id}`,'PUT');await page.locator('#editor-dialog').waitFor({state:'hidden'});
  const anonymous=await browser.newContext({viewport:{width:1440,height:1000}}),homePage=await anonymous.newPage();watch(homePage);await homePage.goto(origin+'/');const publicDesign=homePage.frameLocator('.design-frame');await publicDesign.locator('canvas').waitFor({state:'visible'});assert.ok(Number(await publicDesign.locator('canvas').getAttribute('data-triangles'))>0);
  for(const width of [1440,390]){await homePage.setViewportSize({width,height:1000});assert.ok(await homePage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'3D home must fit');await screenshot(homePage,`home-three-${width}`);}
  await anonymous.close();
  const reduced=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),reducedPage=await reduced.newPage();watch(reducedPage);await reducedPage.goto(origin+'/');await reducedPage.frameLocator('.design-frame').locator('canvas').waitFor({state:'visible'});assert.equal(await reducedPage.frameLocator('.design-frame').locator('#toggle-motion').getAttribute('aria-pressed'),'true');await reduced.close();
  const fallbackContext=await browser.newContext({viewport:{width:390,height:844}});await fallbackContext.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};});const fallbackPage=await fallbackContext.newPage();await fallbackPage.goto(origin+'/');await fallbackPage.frameLocator('.design-frame').locator('#fallback').waitFor({state:'visible'});assert.equal(await fallbackPage.frameLocator('.design-frame').locator('h2').innerText(),'ایده شما در بُعدی تازه');await fallbackContext.close();
  // Upload a real embedded-texture model and font, then exercise the designer UI and public runtime.
  await page.locator('[data-view=designer]').click();
  for(const [name,mimeType,buffer] of [['product.glb','model/gltf-binary',modelGLB()],['brand.woff','font/woff',brandFont]]){
    const assetForm=page.locator('#design-asset-upload');await assetForm.locator('[name=asset]').setInputFiles({name,mimeType,buffer});await submit(assetForm,'/api/media');await page.getByText(name,{exact:true}).waitFor();
  }
  await page.locator('[data-new-design=glb-hero]').click();await designDialog.waitFor({state:'visible'});await codeFrame.locator('canvas[data-model-loaded=true]').waitFor({state:'visible'});assert.ok(Number(await codeFrame.locator('canvas').getAttribute('data-triangles'))>0,'Embedded GLB texture must load and render');
  await designDialog.locator('summary').filter({hasText:'دارایی‌های مجاز طرح'}).click();await designDialog.locator('[data-insert-font]').click();await designDialog.locator('#refresh-design').click();await codeFrame.locator('canvas[data-model-loaded=true]').waitFor();await codeFrame.locator('body').evaluate(()=>document.fonts.ready);assert.equal(await codeFrame.locator('body').evaluate(()=>document.fonts.check('16px CMSBrand','CMS Brand Test')),true,'Uploaded WOFF must decode');assert.equal(await codeFrame.locator('body').evaluate(()=>Array.from(document.fonts).some(f=>f.family==='CMSBrand' && f.status==='loaded')),true);assert.match(await codeFrame.locator('body').evaluate(()=>getComputedStyle(document.body).fontFamily),/CMSBrand/);
  await screenshot(page,'designer-glb-font');await designDialog.locator('#release-form [name=currentPassword]').fill(password);const glbId=app.db.prepare("SELECT id FROM designs WHERE name='نمایش مدل GLB'").get().id;await submit(designDialog.locator('#release-form'),`/api/designs/${glbId}/publish`);
  const glbDesign=app.db.prepare("SELECT * FROM designs WHERE name='نمایش مدل GLB'").get();await designDialog.locator('#close-design').click();const glbPage=putContent(app.db,{kind:'pages',title:'GLB Product',slug:'glb-product',status:'published',excerpt:'Product',body:'',seo_title:'',seo_description:'',blocks:[{type:'code-design',designId:glbDesign.id,title:'GLB Product',height:560}]});
  const glbPublicContext=await browser.newContext({viewport:{width:390,height:844}}),glbPublic=await glbPublicContext.newPage();watch(glbPublic);await glbPublic.goto(origin+'/glb-product/');await glbPublic.frameLocator('.design-frame').locator('canvas[data-model-loaded=true]').waitFor();assert.ok(Number(await glbPublic.frameLocator('.design-frame').locator('canvas').getAttribute('data-triangles'))>0);await glbPublic.frameLocator('.design-frame').locator('body').evaluate(()=>document.fonts.ready);assert.equal(await glbPublic.frameLocator('.design-frame').locator('body').evaluate(()=>document.fonts.check('16px CMSBrand','CMS Brand Test')),true);assert.equal(await glbPublic.frameLocator('.design-frame').locator('body').evaluate(()=>Array.from(document.fonts).some(f=>f.family==='CMSBrand' && f.status==='loaded')),true);await screenshot(glbPublic,'public-glb-font');await glbPublicContext.close();
  // Exercise malicious custom JS in an isolated preview, with expected CSP violations collected separately.
  await page.locator('[data-view=designer]').click();await page.locator('[data-new-design=blank]').click();await page.locator('#design-dialog').waitFor({state:'visible'});await designDialog.locator('[data-code-tab=js]').click();await designDialog.locator('[name=js]').fill(`let result={};for(const key of ['parent','cookie','storage']){try{result[key]=key==='parent'?parent.document.body.innerHTML:key==='cookie'?document.cookie:localStorage.length;}catch{result[key]='blocked';}}fetch('/api/settings').then(()=>result.fetch='allowed').catch(()=>result.fetch='blocked');setTimeout(()=>{document.querySelector('h2').textContent=JSON.stringify(result);parent.postMessage({channel:'cms-design',type:'log',text:'<img src=x onerror=alert(1)>'},'*');},250);`);
  const errorStart=errors.length;await designDialog.locator('#refresh-design').click();await codeFrame.locator('h2').filter({hasText:'"fetch":"blocked"'}).waitFor();assert.equal(JSON.parse(await codeFrame.locator('h2').innerText()).parent,'blocked');assert.equal(JSON.parse(await codeFrame.locator('h2').innerText()).cookie,'blocked');assert.equal(JSON.parse(await codeFrame.locator('h2').innerText()).storage,'blocked');assert.equal(await designDialog.locator('#design-console img').count(),0);const expectedViolations=errors.splice(errorStart);assert.ok(expectedViolations.every(e=>/connect-src .*design-preview.*assets\/|Fetch API cannot load http:\/\/127\.0\.0\.1:\d+\/api\/settings\. Refused to connect because it violates the document's Content Security Policy/.test(e)), 'Only the intentional blocked fetch may violate CSP: '+JSON.stringify(expectedViolations));await designDialog.locator('#close-design').click();
  await page.locator('[data-view=security]').click();await page.locator('#mfa-start [name=password]').fill(password);await submit(page.locator('#mfa-start'),'/api/auth/mfa/setup');await page.locator('#mfa-enrollment').waitFor({state:'visible'});const secret=await page.locator('#mfa-secret').inputValue();await page.locator('#mfa-confirm [name=code]').fill(totp(secret));await submit(page.locator('#mfa-confirm'),'/api/auth/mfa/confirm');await page.locator('#recovery-dialog').waitFor({state:'visible'});const codes=(await page.locator('#recovery-codes').inputValue()).split('\n');assert.equal(codes.length,10);await page.locator('#save-codes').click();await login(password,codes[0]);
  await page.locator('[data-view=security]').click();await page.getByText('ورود دومرحله‌ای فعال است',{exact:true}).waitFor({state:'visible'});await page.locator('#logout').click();await page.locator('#login-form').waitFor({state:'visible'});await page.locator('#forgot-password').click();await page.locator('#forgot-form [name=email]').fill('admin@example.test');await submit(page.locator('#forgot-form'),'/api/auth/forgot-password');
  while(app.db.prepare("SELECT id FROM mail_outbox WHERE status='waiting' AND next_attempt_at<=?").get(Date.now()))await app.flushMail();const token=sent.findLast(message=>message.subject==='بازیابی رمز Core CMS').text.match(/#token=([a-f0-9]{64})/)[1];
  await page.goto(origin+`/admin/reset-password/#token=${token}`);await page.locator('#reset-form').waitFor({state:'visible'});assert.equal(page.url(),origin+'/admin/reset-password/');assert.equal(await page.locator('#login-form').isVisible(),false);
  const reset=page.locator('#reset-form');await reset.locator('[name=newPassword]').fill(newPassword);await reset.locator('[name=repeatPassword]').fill(newPassword);await reset.locator('[name=mfaCode]').fill(codes[1]);await submit(reset,'/api/auth/reset-password');await page.waitForURL(origin+'/admin/');await login(newPassword,codes[2]);
  const site=getSite(app.db);saveSite(app.db,{...site,name:'A'.repeat(100)});app.db.prepare('UPDATE content SET title=? WHERE id=?').run('B'.repeat(200),item.id);await publicPage.reload();assert.ok(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Long brand/title must wrap on mobile');saveSite(app.db,site);
  // Verify the static hosting contract at a separate origin with required CORS/CSP headers.
  await app.close();const output=join(dir,'export');let staticOrigin;
  staticServer=http.createServer(async(req,res)=>{try{const url=new URL(req.url,staticOrigin);if(!url.pathname.startsWith('/client/')){res.writeHead(404);res.end();return;}let path=url.pathname.slice('/client/'.length);if(!path || path.endsWith('/'))path+='index.html';if(path.includes('..'))throw new Error('invalid path');const data=await readFile(join(output,path));if(path.startsWith('design-runtime/') || path.startsWith('design-vendor/')){res.setHeader('Access-Control-Allow-Origin','*');if(path.endsWith('.html'))res.setHeader('Content-Security-Policy',`sandbox allow-scripts; frame-ancestors ${staticOrigin}`);}res.setHeader('Content-Type',path.endsWith('.html')?'text/html':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'application/octet-stream');res.end(data);}catch{res.writeHead(404);res.end();}});
  await new Promise(resolve=>staticServer.listen(0,'127.0.0.1',resolve));staticOrigin=`http://127.0.0.1:${staticServer.address().port}`;await exportSite({dbPath:join(dir,'cms.sqlite'),outputDir:output,publicURL:staticOrigin+'/client'});
  const staticContext=await browser.newContext({viewport:{width:390,height:844}}),staticPage=await staticContext.newPage();watch(staticPage);await staticPage.goto(staticOrigin+'/client/');await staticPage.frameLocator('.design-frame').locator('canvas[data-renderer=three]').waitFor({state:'visible'});assert.ok(Number(await staticPage.frameLocator('.design-frame').locator('canvas').getAttribute('data-triangles'))>0,'Static Three.js export must render');assert.ok(await staticPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await staticPage.frameLocator('.design-frame').locator('body').evaluate(()=>{try{return parent.document.body.innerHTML;}catch{return 'blocked';}}),'blocked');await screenshot(staticPage,'static-three-mobile');
  await staticPage.goto(staticOrigin+'/client/glb-product/');await staticPage.frameLocator('.design-frame').locator('canvas[data-model-loaded=true]').waitFor();assert.ok(Number(await staticPage.frameLocator('.design-frame').locator('canvas').getAttribute('data-triangles'))>0,'Static GLB must render with embedded texture');await staticPage.frameLocator('.design-frame').locator('body').evaluate(()=>document.fonts.ready);assert.equal(await staticPage.frameLocator('.design-frame').locator('body').evaluate(()=>document.fonts.check('16px CMSBrand','CMS Brand Test')),true);assert.equal(await staticPage.frameLocator('.design-frame').locator('body').evaluate(()=>Array.from(document.fonts).some(f=>f.family==='CMSBrand' && f.status==='loaded')),true);await screenshot(staticPage,'static-glb-font');
  await staticPage.goto(staticOrigin+`/client/design-runtime/${design.id}/${design.published_id}/index.html`);assert.equal(await staticPage.evaluate(()=>{try{return document.cookie;}catch{return 'blocked';}}),'blocked','Direct static runtime requires HTTP sandbox');await staticContext.close();
  assert.deepEqual(errors,[]);console.log(`Browser smoke passed (${await browser.version()}): theme, image upload, sections/reordering, draft preview, publication, desktop/mobile, designer autosave/history/presets/drag, Three.js and embedded GLB/WOFF WebGL/reduced-motion/fallback/sandbox/static export, MFA and password recovery. SMTP used a mock sender.`);
}finally{if(staticServer?.listening)await new Promise(resolve=>staticServer.close(resolve));await browser?.close();await app.close();await rm(dir,{recursive:true,force:true});}
